# Generated by Django 5.1.4 on 2025-08-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(blank=True, default='S,M,L,XL,XXL', max_length=100),
        ),
    ]
